#active
spring:
    profiles:
        active: dev

#server.port=8065

#mysql  useLegacyDatetimeCode=false&serverTimezone=GMT-8 use beijing time Asia/Shanghai  &useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#spring.datasource.url=jdbc:mysql://47.98.164.44:3306/coffeemachine?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#The password of 47.98.164.44:3306 is mxs123456
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#datasource pool
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.druid.initial-size=8
#spring.datasource.druid.min-idle=5
#spring.datasource.druid.max-active=10
#spring.datasource.druid.query-timeout=6000
#spring.datasource.druid.transaction-query-timeout=6000
#spring.datasource.druid.remove-abandoned-timeout=1800
#spring.datasource.druid.filter-class-names=stat
#spring.datasource.druid.filters=stat,config

#spring.datasource.secondary.url=jdbc:mysql://localhost:3306/ssm
#spring.datasource.secondary.username=root
#spring.datasource.secondary.password=root
#spring.datasource.secondary.driver-class-name=com.mysql.jdbc.Driver

#show sql and auto to update table
#spring.jpa.hibernate.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#management.security.enabled=false

#time format
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+8
    
#\u914d\u7f6e\u6a21\u677f\u5f15\u64ce
#spring.thymeleaf.prefix=classpath:templates/
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html
#spring.thymeleaf.cache=false


#\u914d\u7f6e\u4f7f\u7528\u54ea\u4e2a\u914d\u7f6e\u6587\u4ef6 \u5f53\u524d\u6587\u4ef6\u65f6\u4f4f\u914d\u7f6e\u6587\u4ef6
#spring.profiles.active=dev/test/prod
#dev/test/prod   \u672c\u5730\u3001\u6d4b\u8bd5\u3001\u6b63\u5f0f


#Redis configuration
#spring.redis.database=0
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.password=
#spring.redis.pool.max-active=8
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.pool.max-wait=0
#spring.redis.timeout=0

#MongoDB
#spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/test
#\uff08\u7528\u6237\u540d\u4e3aname\uff0c\u5bc6\u7801\u4e3apass\uff09    
#\u82e5\u4f7f\u7528mongodb 2.x\uff0c\u4e5f\u53ef\u4ee5\u901a\u8fc7\u5982\u4e0b\u53c2\u6570\u914d\u7f6e\uff0c\u8be5\u65b9\u5f0f\u4e0d\u652f\u6301mongodb 3.x
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodn.database=
#spring.data.mongodb.authenticationDatabase=admin
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root


#spring.aop.auto=true 
# Add @EnableAspectJAutoProxy.
#spring.aop.proxy-target-class=true 
# Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).

#Zookeeper
#dubbo.registry.address=localhost:2281

logging:
    level:
        root: INFO

#email
#spring.mail.host=smtp.126.com
#spring.mail.username=cmlk123@126.com
#spring.mail.port=465
#spring.mail.password=liukun123456
#spring.mail.properties.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.default-encoding=UTF-8
 
                    